[[ -r ~/.bashrc ]] && source ~/.bashrc

if [ $(uname) == "Darwin" ] ; then
    # add MacPorts paths, if it's installed...
    if [ -x /opt/local/bin/port ] ; then
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
    fi
    if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
        . /opt/local/etc/profile.d/bash_completion.sh
    fi
fi

if [ -e ~/.profile ] ; then
    source ~/.profile
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
