[[ -r ~/.bashrc ]] && source ~/.bashrc

if [ $(uname) == "Darwin" ] ; then
    # add MacPorts paths, if it's installed...
    if [ -x /opt/local/bin/port ] ; then
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
    fi
fi

source ~/.profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
