###
# Bash-specific configuration.
###

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

_configdir="$HOME/eapconfig/dotfiles"

source_if_exists () {
  [[ -e "$1" ]] && source "$1"
}

# Bash stuff.
source_if_exists "$_configdir/bashrc-aliases"
source_if_exists "$_configdir/bashrc-completion"
source_if_exists "$_configdir/bashrc-functions"
source_if_exists "$_configdir/bashrc-prompt"

# Hooks for Bash configuration from sources other than this repo.
source_if_exists ~/.bashrc_local
source_if_exists ~/.bashrc_private

# Save a bunch of history.
HISTSIZE=10000
HISTFILESIZE=100000
HISTTIMEFORMAT="%a %b %d %T %Z %Y "
# Don't put duplicate lines or lines prefixed with whitespace in history.
HISTCONTROL=ignoredups:ignorespace
# Append to history file, don't overwrite it.
shopt -s histappend
