#!/bin/bash

# cd
alias         ..="cd ../"
alias        ...="cd ../../"
alias       ....="cd ../../../"
alias      .....="cd ../../../../"
alias     ......="cd ../../../../../"
alias    .......="cd ../../../../../../"
alias   ........="cd ../../../../../../../"
alias  .........="cd ../../../../../../../../"
alias ..........="cd ../../../../../../../../../"

# grep
alias grep="grep --color=always --exclude-dir={.svn,.git}"

# less
alias less="less -r"  # maintain control characters (for color, essentially)

# ls
if [[ $OSTYPE == darwin* ]] ; then
    alias ls="ls -G"
else
    alias ls="ls --color=always"
fi
alias list="ls -alh"
alias lsit="list"

# pep8
alias pep8="pep8 --repeat"

# docker
alias docker-rm-exited='docker rm $(docker ps -a -q -f "status=exited")'
alias docker-rm-untagged='docker rmi $(docker images -q -f "dangling=true")'

# other 
alias :q="echo This isn\'t vim\!"
alias manhtml="man --html"
