###
# Entry point for Bash.
###

source_if_exists () {
    [[ -e "$1" ]] && source "$1"
}

# Keep it simple; just source .profile, then .bashrc.
# See: https://superuser.com/a/789465
source_if_exists "$HOME/.profile"
source_if_exists "$HOME/.bashrc"

# vim: ft=sh
